### ISSUE TITLE
Module dependency graph for reloading

### ISSUE THREAD

**Issue by orta** [alloy/relational-theory#5]
This is something handled by [a Haste Map](http://artsy.github.io/blog/2016/11/14/JS-Glossary/#haste-map) [in Jest](https://github.com/facebook/jest/tree/master/packages/jest-haste-map/src).

That said - flow _does_ have something for this:

```
npm run flow -- get-imports app/containers/artist/index.js

> relational-theory@0.0.1 flow /Users/orta/dev/js/apps/relational-theory
> flow "get-imports" "app/containers/artist/index.js"

Imports for module 'app/containers/artist/index.js':
	/Users/orta/dev/js/apps/relational-theory/data/graphql-export.flow.js@/Users/orta/dev/js/apps/relational-theory/app/containers/artist/index.js:6:33,6:67
	/Users/orta/dev/js/apps/relational-theory/app/containers/artist/components/header.js@/Users/orta/dev/js/apps/relational-theory/app/containers/artist/index.js:5:26,5:46
	react-relay@/Users/orta/dev/js/apps/relational-theory/app/containers/artist/index.js:4:19,4:31
	react@/Users/orta/dev/js/apps/relational-theory/app/containers/artist/index.js:13:7,13:11
```

**Comment by orta** [comment]
And flow is compiled to JS as a npm module, so you may be able to do ^ without the process call - not 100% on that

**Comment by orta** [comment]
This above only works if you have `@flow` in every file, which I have a branch of now

**Comment by orta** [comment]
https://github.com/orta/relational-theory/commit/b3140ad18cef7625b3e6eb411bb0ffec7fbdf0b8

**Comment by alloy** [comment]
Dope. Normally I’d probably go for using Jest’s `HasteMap` because it probably has less dependencies than `flow`, but we already depend on both, they’re only needed in development, and the API seems complicated whereas maybe Flow’s is simple? Let’s go with whichever of the two has the simplest API and less impact in our source.

**Comment by alloy** [comment]
PS I assume you’ll PR that flow branch?

**Comment by orta** [comment]
yes

**Comment by orta** [comment]
soon

**Comment by alloy** [comment]
Closing this in response to #10.
